### ISSUE TITLE
Align with gmock 1.10.0

### ISSUE THREAD

**Issue by TurtleWithWheels156** [apriorit/gmock-more-args#2]
Working on using gmock 1.10.0 and this library and came across a compatibility issue. Seeing how it went up to 1.8.1, I am looking to see if this repo can provide another update. Gives the same error as the previous issue opened (internal::FunctionMockerBase declaration is not visible any more)

**Comment by SergiusTheBest** [comment]
We'll check that out. Thank you!

**Comment by SergiusTheBest** [comment]
@TurtleWithWheels156 We tested with 1.10.0 and it worked with no issues. Are you sure you were using the latest gmock-more-args?

**Comment by TurtleWithWheels156** [comment]
Hi Sergius, thanks for the response. I wanted to let you know that it did compile with the gmock version in question.  Still looking into the reason, but we ended up using a makefile from a previous version that worked well with our builds compared to the cmake files.

**Comment by SergiusTheBest** [comment]
That's strange. We've tested on [gmock-more-args-sample](https://github.com/apriorit/gmock-more-args-sample) (with updated submodule to 1.10.0). It uses cmake and compiles fine.

Ok, then I'm closing the issue.
